### ISSUE TITLE
The sparc model for platofms needs an interrupt port

### ISSUE THREAD

**Issue by lianaduenha** [ArchC/sparc#1]
The sparc_block.ac and sparc_nonblock.ac files define the sparc model for its use in platforms. So, we need to define an interrupt port, just as we did in the other processors.

I suggest to add the following code line in these files:

ac_tlm2_intr_port intr_port;

**Comment by maxiwell** [comment]
I agree. Submit a Pull Request with this modification.

**Comment by maxiwell** [comment]
PR #2
